### ISSUE TITLE
Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by raner** [boxheed/gradle-pater-build-plugin#3] opened 2015-04-07 21:05 UTC
I tried this plugin and it appears that it is having trouble reading the packaged common.gradle file...
Full output with --info:

[sts] -----------------------------------------------------
[sts] Starting Gradle build for the following tasks:
[sts]      build
[sts]      printScmVersionTag
[sts] -----------------------------------------------------
The client will now receive all logging from the daemon (pid: 5768). The daemon log file: C:\Users\ranermir.gradle\daemon\2.2.1\daemon-5768.out.log
Executing build with daemon context: DefaultDaemonContext[uid=6eb9597c-fc0f-4b6f-b389-9c5bf76943a0,javaHome=C:\Program Files\Java\jdk1.8.0_20,daemonRegistryDir=C:\Users\ranermir.gradle\daemon,pid=5768,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]
Closing daemon's stdin at end of input.
The daemon will no longer process any standard input.
Starting Build
Settings evaluated using settings file 'C:\Users\ranermir\Git\trading-controls\settings.gradle'.
Projects loaded. Root project using build file 'C:\Users\ranermir\Git\trading-controls\build.gradle'.
Included projects: [root project 'Trading Controls', project ':Trading Controls App', project ':Trading Controls Tests']
Evaluating root project 'Trading Controls' using build file 'C:\Users\ranermir\Git\trading-controls\build.gradle'.
axis#axis-jaxrpc;1.4 is relocated to org.apache.axis#axis-jaxrpc;1.4. Please update your dependencies.
axis#axis-saaj;1.4 is relocated to org.apache.axis#axis-saaj;1.4. Please update your dependencies.
Using build file resolvers: [com.fizzpod.gradle.plugins.pater.ClasspathGradleBuildFileResolver@57f4c581]
Reflections took 6 ms to scan 1 urls, producing 1 keys and 1 values
Discovered build files: [META-INF/pater-build/common.gradle]

FAILURE: Build failed with an exception.
- Where:
  Build file 'C:\Users\ranermir\Git\trading-controls\build.gradle' line: 13
- What went wrong:
  A problem occurred evaluating root project 'Trading Controls'.
  
  > Failed to apply plugin [id 'com.fizzpod.pater-build']
  > Unexpected end of ZLIB input stream
- Try:
  Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 0.39 secs
[sts] Build failed
org.gradle.tooling.BuildException: Could not execute build using Gradle installation 'C:\Users\ranermir\Gradle\gradle-2.2.1'.
       at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:53)
       at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
       at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       at java.lang.Thread.run(Thread.java:745)
       at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
       at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:71)
       at org.springsource.ide.eclipse.gradle.core.TaskUtil.execute(TaskUtil.java:117)
       at org.springsource.ide.eclipse.gradle.core.launch.GradleProcess$1.doit(GradleProcess.java:92)
       at org.springsource.ide.eclipse.gradle.core.util.GradleRunnable$1.run(GradleRunnable.java:53)
       at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file 'C:\Users\ranermir\Git\trading-controls\build.gradle' line: 13
A problem occurred evaluating root project 'Trading Controls'.
       at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:77)
       at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:47)
       at org.gradle.initialization.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30)
       at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:108)
       at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
       at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
       at org.gradle.tooling.internal.provider.BuildModelAction.run(BuildModelAction.java:43)
       at org.gradle.tooling.internal.provider.BuildModelAction.run(BuildModelAction.java:30)
       at org.gradle.tooling.internal.provider.ConfiguringBuildAction.run(ConfiguringBuildAction.java:119)
       at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
       at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
       at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:47)
       at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
       at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
       at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:35)
       at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
       at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
       at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
       at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
       at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
       at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
       at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:69)
       at org.gradle.util.Swapper.swap(Swapper.java:38)
       at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:69)
       at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
       at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
       at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
       at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
       at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:70)
       at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
       at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
       at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(DaemonHygieneAction.java:39)
       at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
       at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:46)
       at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
       at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
Caused by: org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'Trading Controls'.
       at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
       at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:148)
       at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
       at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
       at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
       at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:59)
       at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
       at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:83)
       at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
       at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
       at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
       at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
       ... 32 more
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'com.fizzpod.pater-build']
       at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:117)
       at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
       at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
       at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:131)
       at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:37)
       at org.gradle.api.Project$apply$10.call(Unknown Source)
       at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
       at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
       at build_7cy36nhxl9fexw8wwtbw8jcos.run(C:\Users\ranermir\Git\trading-controls\build.gradle:13)
       at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
       ... 43 more
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
       at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
       at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
       at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
       at org.apache.commons.io.IOUtils$copy.call(Unknown Source)
       at com.fizzpod.gradle.plugins.pater.ClasspathGradleBuildFileResolver.exportBuildFile(ClasspathGradleBuildFileResolver.groovy:59)
       at com.fizzpod.gradle.plugins.pater.ClasspathGradleBuildFileResolver.exportBuildFiles(ClasspathGradleBuildFileResolver.groovy:39)
       at com.fizzpod.gradle.plugins.pater.ClasspathGradleBuildFileResolver.this$2$exportBuildFiles(ClasspathGradleBuildFileResolver.groovy)
       at com.fizzpod.gradle.plugins.pater.ClasspathGradleBuildFileResolver$this$2$exportBuildFiles.callCurrent(Unknown Source)
       at com.fizzpod.gradle.plugins.pater.ClasspathGradleBuildFileResolver.findBuildFiles(ClasspathGradleBuildFileResolver.groovy:24)
       at com.fizzpod.gradle.plugins.pater.GradleBuildFileResolver$findBuildFiles.call(Unknown Source)
       at com.fizzpod.gradle.plugins.pater.PaterPlugin$_resolveBuildFiles_closure2.doCall(PaterPlugin.groovy:41)
       at com.fizzpod.gradle.plugins.pater.PaterPlugin.resolveBuildFiles(PaterPlugin.groovy:40)
       at com.fizzpod.gradle.plugins.pater.PaterPlugin.this$2$resolveBuildFiles(PaterPlugin.groovy)
       at com.fizzpod.gradle.plugins.pater.PaterPlugin$this$2$resolveBuildFiles.callCurrent(Unknown Source)
       at com.fizzpod.gradle.plugins.pater.PaterPlugin.apply(PaterPlugin.groovy:18)
       at com.fizzpod.gradle.plugins.pater.PaterPlugin.apply(PaterPlugin.groovy)
       at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
       at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
       at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:103)
       at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:115)
       ... 52 more
[sts] Time taken: 0 min, 0 sec
[sts] -----------------------------------------------------

**Comment by boxheed** [comment] 2015-04-07 21:43
Can you provide a scenario that reproduces this problem?

**Comment by raner** [comment] 2015-04-07 22:39
Unfortunately, not easily. This is part of proprietary work that I'm doing for my employer (or rather my employer's client).
If it helps at all, the common.gradle file that I'm trying to include is 2868 bytes long, and the ZLIB EOFException consistently happens after reading 2787 bytes. Maybe it's related to the file length? Have you tried it with longer Gradle scripts?

BTW, on an unrelated matter, during my debugging efforts I also ran into problems with the 0-byte files under META-INF/services. The ServiceLoader apparently cannot handle zero-length files. It seems that the files should have been removed from the repo; why are they kept around as empty files?

**Comment by raner** [comment] 2015-04-07 22:44
Also, I have manually opened the JAR to make sure it is not corrupted. So, the JAR itself seems to be fine.

**Comment by boxheed** [comment] 2015-04-07 22:55
Interesting, what OS and JDK are you using?

**Comment by raner** [comment] 2015-04-08 14:20
64-bit Windows 7 SP 1, JDK 1.8.0 update 31.

**Comment by boxheed** [comment] 2015-04-09 23:02
Hi, I've updated the simple-build-script example to have a large gradle build file in it. Can you check out the source and run it, do a `gradle clean install` and then `gradle -b usage.gradle tasks -i`

**Comment by raner** [comment] 2015-04-15 04:45
Hi, sorry for the lag. This story got put on the back burner for now, we'll let you know what we find when we pick it up again.

**Comment by boxheed** [comment] 2015-04-15 10:37
ok, thanks

**Comment by boxheed** [comment] 2015-12-08 23:22
Hi Raner, just doing a bit of house-keeping and wondered whether you have re-visited this. If not I will close the issue.

**Comment by boxheed** [comment] 2017-07-17 08:06
Thanks @raner for raising this, but as I am unable to reproduce and this issue has not been updated in a long time I am closing it.

**Closed by boxheed** 2017-07-17 08:06 UTC
